version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - "2.13.1"

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

before_install:
  - git fetch --tags

script: sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues test scalafmtCheckAll scalafmtSbtCheck

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: release
      env: ADOPTOPENJDK=8
      script: sbt ci-release
