addSbtPlugin("com.codecommit"                    % "sbt-github-actions" % "0.14.0")
addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"     % "1.5.10")
addSbtPlugin("com.typesafe"                      % "sbt-mima-plugin"    % "1.0.1")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"       % "2.4.3")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"   % "3.0.0")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"      % "1.9.2")
addSbtPlugin("org.scoverage"                     % "sbt-coveralls"      % "1.3.1")
