addSbtPlugin("com.codecommit"                    % "sbt-github-actions" % "0.13.0")
addSbtPlugin("com.geirsson"                      % "sbt-ci-release"     % "1.5.7")
addSbtPlugin("com.typesafe"                      % "sbt-mima-plugin"    % "0.9.2")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"       % "2.4.3")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"   % "3.0.0")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"      % "1.8.2")
addSbtPlugin("org.scoverage"                     % "sbt-coveralls"      % "1.3.1")
